#ifndef MANTID_NEXUSGEOMETRY_DLL_H
#define MANTID_NEXUSGEOMETRY_DLL_H

#define MANTID_NEXUSGEOMETRY_DLL
#define MANTID_NEXUSGEOMETRY_NO_EXPORT

#ifndef MANTID_NEXUSGEOMETRY_DEPRECATED
#  define MANTID_NEXUSGEOMETRY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_NEXUSGEOMETRY_DEPRECATED_EXPORT
#  define MANTID_NEXUSGEOMETRY_DEPRECATED_EXPORT MANTID_NEXUSGEOMETRY_DLL MANTID_NEXUSGEOMETRY_DEPRECATED
#endif

#ifndef MANTID_NEXUSGEOMETRY_DEPRECATED_NO_EXPORT
#  define MANTID_NEXUSGEOMETRY_DEPRECATED_NO_EXPORT MANTID_NEXUSGEOMETRY_NO_EXPORT MANTID_NEXUSGEOMETRY_DEPRECATED
#endif

#ifndef NEXUSGEOMETRY_DEPRECATED
    #define NEXUSGEOMETRY_DEPRECATED(func) MANTID_NEXUSGEOMETRY_DEPRECATED func
#endif

// MantidKernel/System.h will be removed
#include "MantidKernel/System.h"

// Use extern keyword in client code to suppress class template instantiation
#ifdef NexusGeometry_EXPORTS
#define EXTERN_MANTID_NEXUSGEOMETRY
#else
// EXTERN_IMPORT is defined in MantidKernel/System.h

#define EXTERN_MANTID_NEXUSGEOMETRY EXTERN_IMPORT
#endif /* NexusGeometry_EXPORTS*/

 
#endif /* MANTID_NEXUSGEOMETRY_DLL_H */
