test("MaterialBuilder", () => {
  let result = global.pyodide.runPython(`
    import pytest
    import micromantid
    builder = micromantid.kernel.MaterialBuilder()
    mat = builder.setFormula("Li F6").setMassDensity(0.1).build()
    assert mat.numberDensity == pytest.approx(0.0034858594422501514, 0.000001)
  `);
});

test("api_ADSValidatorTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/ADSValidatorTest") `); })
//test("api_AlgoRegisterTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgoRegisterTest") `); })
//test("api_AlgorithmFactoryObserverTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmFactoryObserverTest") `); })
//test("api_AlgorithmFactoryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmFactoryTest") `); })
//test("api_AlgorithmHistoryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmHistoryTest") `); })
//test("api_AlgorithmManagerTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmManagerTest") `); })
//test("api_AlgorithmPropertyTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmPropertyTest") `); })
//test("api_AlgorithmTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AlgorithmTest") `); })
//test("api_AnalysisDataServiceObserverTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AnalysisDataServiceObserverTest") `); })
//test("api_AnalysisDataServiceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AnalysisDataServiceTest") `); })
//test("api_AxisTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/AxisTest") `); })
//test("api_CatalogManagerTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/CatalogManagerTest") `); })
//test("api_CompositeFunctionTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/CompositeFunctionTest") `); })
//test("api_DataProcessorAlgorithmTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/DataProcessorAlgorithmTest") `); })
//test("api_DeprecatedAlgorithmCheckerTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/DeprecatedAlgorithmCheckerTest") `); })
//test("api_ExperimentInfoTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/ExperimentInfoTest") `); })
//test("api_FileFinderTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/FileFinderTest") `); })
//test("api_FilePropertyTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/FilePropertyTest") `); })
//test("api_FrameworkManagerTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/FrameworkManagerTest") `); })
//test("api_FunctionFactoryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/FunctionFactoryTest") `); })
//test("api_FunctionPropertyTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/FunctionPropertyTest") `); })
//test("api_IEventWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IEventWorkspaceTest") `); })
//test("api_IFunction1DTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IFunction1DTest") `); })
//test("api_IFunction1DValidatorTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IFunction1DValidatorTest") `); })
//test("api_IMaskWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IMaskWorkspaceTest") `); })
//test("api_IPeakFunctionTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IPeakFunctionTest") `); })
//test("api_IPeaksWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/IPeaksWorkspaceTest") `); })
//test("api_ITableWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/ITableWorkspaceTest") `); })
test("api_JacobianTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/JacobianTest") `); })
//test("api_MatrixWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MatrixWorkspaceTest") `); })
//test("api_MDEventWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MDEventWorkspaceTest") `); })
//test("api_MDGeometryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MDGeometryTest") `); })
//test("api_MDHistoWorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MDHistoWorkspaceTest") `); })
//test("api_MultipleExperimentInfos", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MultipleExperimentInfos") `); })
//test("api_MultipleFilePropertyTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/MultipleFilePropertyTest") `); })
test("api_PreviewManagerTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/PreviewManagerTest") `); })
//test("api_ProgressTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/ProgressTest") `); })
//test("api_ProjectionTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/ProjectionTest") `); })
//test("api_PythonAlgorithmChildAlgCallTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/PythonAlgorithmChildAlgCallTest") `); })
//test("api_PythonAlgorithmPropertiesTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/PythonAlgorithmPropertiesTest") `); })
//test("api_PythonAlgorithmTraitsTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/PythonAlgorithmTraitsTest") `); })
test("api_PythonAlgorithmWorkspacePropertyTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/PythonAlgorithmWorkspacePropertyTest") `); })
//test("api_RunPythonScriptTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/RunPythonScriptTest") `); })
test("api_RunTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/RunTest") `); })
//test("api_SampleTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/SampleTest") `); })
//test("api_SpectrumInfoTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/SpectrumInfoTest") `); })
//test("api_WorkspaceBinaryOpsTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceBinaryOpsTest") `); })
//test("api_WorkspaceFactoryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceFactoryTest") `); })
//test("api_WorkspaceGroupTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceGroupTest") `); })
//test("api_WorkspaceHistoryTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceHistoryTest") `); })
test("api_WorkspacePropertiesTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspacePropertiesTest") `); })
test("api_WorkspaceTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceTest") `); })
//test("api_WorkspaceUnaryOpsTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceUnaryOpsTest") `); })
//test("api_WorkspaceValidatorsTest", () => { let result = global.pyodide.runPython(` import micromantid_test; micromantid_test.run("api/WorkspaceValidatorsTest") `); })
