#ifndef MANTID_CURVEFITTING_DLL_H
#define MANTID_CURVEFITTING_DLL_H

#define MANTID_CURVEFITTING_DLL
#define MANTID_CURVEFITTING_NO_EXPORT

#ifndef MANTID_CURVEFITTING_DEPRECATED
#  define MANTID_CURVEFITTING_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_CURVEFITTING_DEPRECATED_EXPORT
#  define MANTID_CURVEFITTING_DEPRECATED_EXPORT MANTID_CURVEFITTING_DLL MANTID_CURVEFITTING_DEPRECATED
#endif

#ifndef MANTID_CURVEFITTING_DEPRECATED_NO_EXPORT
#  define MANTID_CURVEFITTING_DEPRECATED_NO_EXPORT MANTID_CURVEFITTING_NO_EXPORT MANTID_CURVEFITTING_DEPRECATED
#endif

#ifndef CURVEFITTING_DEPRECATED
    #define CURVEFITTING_DEPRECATED(func) MANTID_CURVEFITTING_DEPRECATED func
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#include <cstdint>

#endif /* MANTID_CURVEFITTING_DLL_H */
