#ifndef MANTID_DATAHANDLING_DLL_H
#define MANTID_DATAHANDLING_DLL_H

#define MANTID_DATAHANDLING_DLL
#define MANTID_DATAHANDLING_NO_EXPORT

#ifndef MANTID_DATAHANDLING_DEPRECATED
#  define MANTID_DATAHANDLING_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_DATAHANDLING_DEPRECATED_EXPORT
#  define MANTID_DATAHANDLING_DEPRECATED_EXPORT MANTID_DATAHANDLING_DLL MANTID_DATAHANDLING_DEPRECATED
#endif

#ifndef MANTID_DATAHANDLING_DEPRECATED_NO_EXPORT
#  define MANTID_DATAHANDLING_DEPRECATED_NO_EXPORT MANTID_DATAHANDLING_NO_EXPORT MANTID_DATAHANDLING_DEPRECATED
#endif

#ifndef DATAHANDLING_DEPRECATED
    #define DATAHANDLING_DEPRECATED(func) MANTID_DATAHANDLING_DEPRECATED func
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#include <cstdint>

#endif /* MANTID_DATAHANDLING_DLL_H */
