#ifndef MANTID_CRYSTAL_DLL_H
#define MANTID_CRYSTAL_DLL_H

#define MANTID_CRYSTAL_DLL
#define MANTID_CRYSTAL_NO_EXPORT

#ifndef MANTID_CRYSTAL_DEPRECATED
#  define MANTID_CRYSTAL_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_CRYSTAL_DEPRECATED_EXPORT
#  define MANTID_CRYSTAL_DEPRECATED_EXPORT MANTID_CRYSTAL_DLL MANTID_CRYSTAL_DEPRECATED
#endif

#ifndef MANTID_CRYSTAL_DEPRECATED_NO_EXPORT
#  define MANTID_CRYSTAL_DEPRECATED_NO_EXPORT MANTID_CRYSTAL_NO_EXPORT MANTID_CRYSTAL_DEPRECATED
#endif

#ifndef CRYSTAL_DEPRECATED
#  define CRYSTAL_DEPRECATED(func) MANTID_CRYSTAL_DEPRECATED func
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#include <cstdint>

#endif /* MANTID_CRYSTAL_DLL_H */
