#ifndef MANTID_ALGORITHMS_DLL_H
#define MANTID_ALGORITHMS_DLL_H

#define MANTID_ALGORITHMS_DLL
#define MANTID_ALGORITHMS_NO_EXPORT

#ifndef MANTID_ALGORITHMS_DEPRECATED
#  define MANTID_ALGORITHMS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_ALGORITHMS_DEPRECATED_EXPORT
#  define MANTID_ALGORITHMS_DEPRECATED_EXPORT MANTID_ALGORITHMS_DLL MANTID_ALGORITHMS_DEPRECATED
#endif

#ifndef MANTID_ALGORITHMS_DEPRECATED_NO_EXPORT
#  define MANTID_ALGORITHMS_DEPRECATED_NO_EXPORT MANTID_ALGORITHMS_NO_EXPORT MANTID_ALGORITHMS_DEPRECATED
#endif

#ifndef ALGORITHMS_DEPRECATED
    #define ALGORITHMS_DEPRECATED(func) MANTID_ALGORITHMS_DEPRECATED func
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#include <cstdint>

#endif /* MANTID_ALGORITHMS_DLL_H */
