set(MTDSRCDIR ../mantid/Framework/Algorithms)

set(SRC_FILES
    ${MTDSRCDIR}/src/AbsorptionCorrection.cpp
    ${MTDSRCDIR}/src/AddAbsorptionWeightedPathLengths.cpp
    ${MTDSRCDIR}/src/AddLogDerivative.cpp
    ${MTDSRCDIR}/src/AddPeak.cpp
    ${MTDSRCDIR}/src/AddSampleLog.cpp
    ${MTDSRCDIR}/src/AddTimeSeriesLog.cpp
    ${MTDSRCDIR}/src/AlignDetectors.cpp
    ${MTDSRCDIR}/src/AnnularRingAbsorption.cpp
    ${MTDSRCDIR}/src/AnyShapeAbsorption.cpp
    ${MTDSRCDIR}/src/ApodizationFunctions.cpp
    ${MTDSRCDIR}/src/AppendSpectra.cpp
    ${MTDSRCDIR}/src/ApplyCalibration.cpp
    ${MTDSRCDIR}/src/ApplyDetailedBalance.cpp
    ${MTDSRCDIR}/src/ApplyFloodWorkspace.cpp
    ${MTDSRCDIR}/src/ApplyInstrumentToPeaks.cpp
    ${MTDSRCDIR}/src/ApplyTransmissionCorrection.cpp
    ${MTDSRCDIR}/src/AverageLogData.cpp
    ${MTDSRCDIR}/src/BeamProfileFactory.cpp
    ${MTDSRCDIR}/src/Bin2DPowderDiffraction.cpp
    ${MTDSRCDIR}/src/BinaryOperateMasks.cpp
    ${MTDSRCDIR}/src/BinaryOperation.cpp
    ${MTDSRCDIR}/src/CalculateCarpenterSampleCorrection.cpp
    ${MTDSRCDIR}/src/CalculateCountRate.cpp
    ${MTDSRCDIR}/src/CalculateDIFC.cpp
    ${MTDSRCDIR}/src/CalculateDynamicRange.cpp
    ${MTDSRCDIR}/src/CalculateEfficiency.cpp
    ${MTDSRCDIR}/src/CalculateEfficiency2.cpp
    ${MTDSRCDIR}/src/CalculateFlatBackground.cpp
    ${MTDSRCDIR}/src/CalculateIqt.cpp
    ${MTDSRCDIR}/src/CalculatePlaczek.cpp
    ${MTDSRCDIR}/src/CalculatePlaczekSelfScattering.cpp
    ${MTDSRCDIR}/src/CalculatePlaczekSelfScattering2.cpp
    ${MTDSRCDIR}/src/CalculatePolynomialBackground.cpp
    ${MTDSRCDIR}/src/CalculateTransmission.cpp
    ${MTDSRCDIR}/src/CalculateTransmissionBeamSpreader.cpp
    ${MTDSRCDIR}/src/CalculateZscore.cpp
    ${MTDSRCDIR}/src/CarpenterSampleCorrection.cpp
    ${MTDSRCDIR}/src/ChangeBinOffset.cpp
    ${MTDSRCDIR}/src/ChangeLogTime.cpp
    ${MTDSRCDIR}/src/ChangePulsetime.cpp
    ${MTDSRCDIR}/src/ChangePulsetime2.cpp
    ${MTDSRCDIR}/src/ChangeTimeZero.cpp
    ${MTDSRCDIR}/src/ChopData.cpp
#   ${MTDSRCDIR}/src/ClearCache.cpp
    ${MTDSRCDIR}/src/ClearInstrumentParameters.cpp
    ${MTDSRCDIR}/src/ClearMaskFlag.cpp
    ${MTDSRCDIR}/src/CloneWorkspace.cpp
    ${MTDSRCDIR}/src/CombineDiffCal.cpp
    ${MTDSRCDIR}/src/Comment.cpp
    ${MTDSRCDIR}/src/CommutativeBinaryOperation.cpp
    ${MTDSRCDIR}/src/CompareWorkspaces.cpp
    ${MTDSRCDIR}/src/ConjoinWorkspaces.cpp
    ${MTDSRCDIR}/src/ConjoinXRuns.cpp
    ${MTDSRCDIR}/src/ConvertAxesToRealSpace.cpp
    ${MTDSRCDIR}/src/ConvertAxisByFormula.cpp
    ${MTDSRCDIR}/src/ConvertDiffCal.cpp
    ${MTDSRCDIR}/src/ConvertFromDistribution.cpp
    ${MTDSRCDIR}/src/ConvertSpectrumAxis.cpp
    ${MTDSRCDIR}/src/ConvertSpectrumAxis2.cpp
    ${MTDSRCDIR}/src/ConvertTableToMatrixWorkspace.cpp
    ${MTDSRCDIR}/src/ConvertToConstantL2.cpp
    ${MTDSRCDIR}/src/ConvertToDistribution.cpp
    ${MTDSRCDIR}/src/ConvertToEventWorkspace.cpp
    ${MTDSRCDIR}/src/ConvertToHistogram.cpp
    ${MTDSRCDIR}/src/ConvertToMatrixWorkspace.cpp
    ${MTDSRCDIR}/src/ConvertToPointData.cpp
    ${MTDSRCDIR}/src/ConvertUnits.cpp
    ${MTDSRCDIR}/src/ConvertUnitsUsingDetectorTable.cpp
    ${MTDSRCDIR}/src/CopyDataRange.cpp
    ${MTDSRCDIR}/src/CopyDetectorMapping.cpp
    ${MTDSRCDIR}/src/CopyInstrumentParameters.cpp
    ${MTDSRCDIR}/src/CopyLogs.cpp
    ${MTDSRCDIR}/src/CopySample.cpp
    ${MTDSRCDIR}/src/CorelliCalibrationApply.cpp
    ${MTDSRCDIR}/src/CorelliCalibrationDatabase.cpp
    ${MTDSRCDIR}/src/CorelliCrossCorrelate.cpp
    ${MTDSRCDIR}/src/CorrectKiKf.cpp
    ${MTDSRCDIR}/src/CorrectTOFAxis.cpp
    ${MTDSRCDIR}/src/CorrectToFile.cpp
    ${MTDSRCDIR}/src/CreateCalFileByNames.cpp
    ${MTDSRCDIR}/src/CreateDetectorTable.cpp
    ${MTDSRCDIR}/src/CreateDummyCalFile.cpp
    ${MTDSRCDIR}/src/CreateEPP.cpp
    ${MTDSRCDIR}/src/CreateFlatEventWorkspace.cpp
    ${MTDSRCDIR}/src/CreateFloodWorkspace.cpp
    ${MTDSRCDIR}/src/CreateGroupingWorkspace.cpp
    ${MTDSRCDIR}/src/CreateLogPropertyTable.cpp
    ${MTDSRCDIR}/src/CreateLogTimeCorrection.cpp
    ${MTDSRCDIR}/src/CreateMonteCarloWorkspace.cpp
    ${MTDSRCDIR}/src/CreatePSDBleedMask.cpp
    ${MTDSRCDIR}/src/CreatePeaksWorkspace.cpp
    ${MTDSRCDIR}/src/CreateSampleWorkspace.cpp
    ${MTDSRCDIR}/src/CreateSingleValuedWorkspace.cpp
    ${MTDSRCDIR}/src/CreateUserDefinedBackground.cpp
    ${MTDSRCDIR}/src/CreateWorkspace.cpp
    ${MTDSRCDIR}/src/CropToComponent.cpp
    ${MTDSRCDIR}/src/CropWorkspace.cpp
    ${MTDSRCDIR}/src/CropWorkspaceRagged.cpp
    ${MTDSRCDIR}/src/CrossCorrelate.cpp
    ${MTDSRCDIR}/src/CuboidGaugeVolumeAbsorption.cpp
    ${MTDSRCDIR}/src/CylinderAbsorption.cpp
    ${MTDSRCDIR}/src/DeadTimeCorrection.cpp
    ${MTDSRCDIR}/src/DeleteLog.cpp
    ${MTDSRCDIR}/src/DeleteWorkspace.cpp
    ${MTDSRCDIR}/src/DeleteWorkspaces.cpp
    ${MTDSRCDIR}/src/DetectorDiagnostic.cpp
    ${MTDSRCDIR}/src/DetectorEfficiencyCor.cpp
    ${MTDSRCDIR}/src/DetectorEfficiencyCorUser.cpp
    ${MTDSRCDIR}/src/DetectorEfficiencyVariation.cpp
    ${MTDSRCDIR}/src/DiffractionEventCalibrateDetectors.cpp
    ${MTDSRCDIR}/src/DiffractionFocussing.cpp
    ${MTDSRCDIR}/src/DiffractionFocussing2.cpp
    ${MTDSRCDIR}/src/DirectILLTubeBackground.cpp
    ${MTDSRCDIR}/src/DiscusMultipleScatteringCorrection.cpp
    ${MTDSRCDIR}/src/Divide.cpp
    ${MTDSRCDIR}/src/EQSANSCorrectFrame.cpp
    ${MTDSRCDIR}/src/EQSANSResolution.cpp
    ${MTDSRCDIR}/src/EQSANSTofStructure.cpp
    ${MTDSRCDIR}/src/EditInstrumentGeometry.cpp
    ${MTDSRCDIR}/src/ElasticWindow.cpp
    ${MTDSRCDIR}/src/EstimateDivergence.cpp
    ${MTDSRCDIR}/src/EstimateResolutionDiffraction.cpp
    ${MTDSRCDIR}/src/EventWorkspaceAccess.cpp
    ${MTDSRCDIR}/src/Exponential.cpp
    ${MTDSRCDIR}/src/ExponentialCorrection.cpp
    ${MTDSRCDIR}/src/ExportTimeSeriesLog.cpp
    ${MTDSRCDIR}/src/ExtractFFTSpectrum.cpp
    ${MTDSRCDIR}/src/ExtractMask.cpp
    ${MTDSRCDIR}/src/ExtractMaskToTable.cpp
    ${MTDSRCDIR}/src/ExtractSingleSpectrum.cpp
    ${MTDSRCDIR}/src/ExtractSpectra.cpp
    ${MTDSRCDIR}/src/ExtractSpectra2.cpp
    ${MTDSRCDIR}/src/ExtractUnmaskedSpectra.cpp
    ${MTDSRCDIR}/src/FFT.cpp
    ${MTDSRCDIR}/src/FFTDerivative.cpp
    ${MTDSRCDIR}/src/FFTSmooth.cpp
    ${MTDSRCDIR}/src/FFTSmooth2.cpp
    ${MTDSRCDIR}/src/FilterBadPulses.cpp
    ${MTDSRCDIR}/src/FilterByLogValue.cpp
    ${MTDSRCDIR}/src/FilterByTime.cpp
    ${MTDSRCDIR}/src/FilterByXValue.cpp
    ${MTDSRCDIR}/src/FilterEvents.cpp
    ${MTDSRCDIR}/src/FindCenterOfMassPosition.cpp
    ${MTDSRCDIR}/src/FindCenterOfMassPosition2.cpp
    ${MTDSRCDIR}/src/FindDeadDetectors.cpp
    ${MTDSRCDIR}/src/FindDetectorsOutsideLimits.cpp
    ${MTDSRCDIR}/src/FindEPP.cpp
    ${MTDSRCDIR}/src/FindPeakBackground.cpp
    ${MTDSRCDIR}/src/FindPeaks.cpp
    ${MTDSRCDIR}/src/FindPeaksConvolve.cpp
    ${MTDSRCDIR}/src/FitPeak.cpp
    ${MTDSRCDIR}/src/FitPeaks.cpp
    ${MTDSRCDIR}/src/FixGSASInstrumentFile.cpp
    ${MTDSRCDIR}/src/FlatPlateAbsorption.cpp
    ${MTDSRCDIR}/src/GeneralisedSecondDifference.cpp
    ${MTDSRCDIR}/src/GenerateEventsFilter.cpp
    ${MTDSRCDIR}/src/GenerateGoniometerIndependentBackground.cpp
    ${MTDSRCDIR}/src/GenerateIPythonNotebook.cpp
    ${MTDSRCDIR}/src/GeneratePeaks.cpp
    ${MTDSRCDIR}/src/GeneratePythonFitScript.cpp
    ${MTDSRCDIR}/src/GeneratePythonScript.cpp
    ${MTDSRCDIR}/src/GetAllEi.cpp
    ${MTDSRCDIR}/src/GetDetectorOffsets.cpp
    ${MTDSRCDIR}/src/GetEi.cpp
    ${MTDSRCDIR}/src/GetEi2.cpp
    ${MTDSRCDIR}/src/GetEiMonDet3.cpp
    ${MTDSRCDIR}/src/GetQsInQENSData.cpp
    ${MTDSRCDIR}/src/GetTimeSeriesLogInformation.cpp
    ${MTDSRCDIR}/src/GravitySANSHelper.cpp
    ${MTDSRCDIR}/src/GroupToXResolution.cpp
    ${MTDSRCDIR}/src/GroupWorkspaces.cpp
    ${MTDSRCDIR}/src/HRPDSlabCanAbsorption.cpp
    ${MTDSRCDIR}/src/He3TubeEfficiency.cpp
    ${MTDSRCDIR}/src/HyspecScharpfCorrection.cpp
    ${MTDSRCDIR}/src/IQTransform.cpp
    ${MTDSRCDIR}/src/IdentifyNoisyDetectors.cpp
    ${MTDSRCDIR}/src/IntegrateByComponent.cpp
    ${MTDSRCDIR}/src/IntegrateEPP.cpp
    ${MTDSRCDIR}/src/Integration.cpp
    ${MTDSRCDIR}/src/InterpolatingRebin.cpp
    ${MTDSRCDIR}/src/InterpolationOption.cpp
    ${MTDSRCDIR}/src/InvertMask.cpp
    ${MTDSRCDIR}/src/LineProfile.cpp
    ${MTDSRCDIR}/src/Logarithm.cpp
    ${MTDSRCDIR}/src/LorentzCorrection.cpp
    ${MTDSRCDIR}/src/MagFormFactorCorrection.cpp
    ${MTDSRCDIR}/src/MaskBins.cpp
    ${MTDSRCDIR}/src/MaskBinsFromTable.cpp
    ${MTDSRCDIR}/src/MaskBinsFromWorkspace.cpp
    ${MTDSRCDIR}/src/MaskBinsIf.cpp
    ${MTDSRCDIR}/src/MaskDetectorsIf.cpp
    ${MTDSRCDIR}/src/MaskInstrument.cpp
    ${MTDSRCDIR}/src/MaskNonOverlappingBins.cpp
    ${MTDSRCDIR}/src/MatrixWorkspaceAccess.cpp
    ${MTDSRCDIR}/src/Max.cpp
    ${MTDSRCDIR}/src/MaxEnt.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentCalculator.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentEntropyNegativeValues.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentEntropyPositiveValues.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentSpaceComplex.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentSpaceReal.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentTransformFourier.cpp
    ${MTDSRCDIR}/src/MaxEnt/MaxentTransformMultiFourier.cpp
    ${MTDSRCDIR}/src/MaxMin.cpp
    ${MTDSRCDIR}/src/MedianDetectorTest.cpp
    ${MTDSRCDIR}/src/MergeLogs.cpp
    ${MTDSRCDIR}/src/MergeRuns.cpp
    ${MTDSRCDIR}/src/Min.cpp
    ${MTDSRCDIR}/src/Minus.cpp
    ${MTDSRCDIR}/src/ModeratorTzero.cpp
    ${MTDSRCDIR}/src/ModeratorTzeroLinear.cpp
    ${MTDSRCDIR}/src/MonitorEfficiencyCorUser.cpp
    ${MTDSRCDIR}/src/MonteCarloAbsorption.cpp
    ${MTDSRCDIR}/src/MostLikelyMean.cpp
    ${MTDSRCDIR}/src/MultipleScatteringCorrection.cpp
    ${MTDSRCDIR}/src/MultipleScatteringCorrectionDistGraber.cpp
    ${MTDSRCDIR}/src/Multiply.cpp
    ${MTDSRCDIR}/src/MultiplyRange.cpp
    ${MTDSRCDIR}/src/NormaliseByCurrent.cpp
    ${MTDSRCDIR}/src/NormaliseByDetector.cpp
    ${MTDSRCDIR}/src/NormaliseToMonitor.cpp
    ${MTDSRCDIR}/src/NormaliseToUnity.cpp
    ${MTDSRCDIR}/src/OneMinusExponentialCor.cpp
    ${MTDSRCDIR}/src/PDCalibration.cpp
    ${MTDSRCDIR}/src/PDDetermineCharacterizations.cpp
    ${MTDSRCDIR}/src/PDFFourierTransform.cpp
    ${MTDSRCDIR}/src/PDFFourierTransform2.cpp
    ${MTDSRCDIR}/src/PaalmanPingsAbsorptionCorrection.cpp
    ${MTDSRCDIR}/src/PaddingAndApodization.cpp
    ${MTDSRCDIR}/src/ParallaxCorrection.cpp
    ${MTDSRCDIR}/src/Pause.cpp
    ${MTDSRCDIR}/src/PeakParameterHelper.cpp
    ${MTDSRCDIR}/src/PerformIndexOperations.cpp
    ${MTDSRCDIR}/src/Plus.cpp
    ${MTDSRCDIR}/src/PointByPointVCorrection.cpp
    ${MTDSRCDIR}/src/PoissonErrors.cpp
    ${MTDSRCDIR}/src/PolarizationCorrectionFredrikze.cpp
    ${MTDSRCDIR}/src/PolarizationCorrectionWildes.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/DepolarizedAnalyserTransmission.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/FlipperEfficiency.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/PolarizationCorrectionsHelpers.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/PolarizationEfficienciesWildes.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/PolarizerEfficiency.cpp
    ${MTDSRCDIR}/src/PolarizationCorrections/SpinStateValidator.cpp
    ${MTDSRCDIR}/src/PolarizationEfficiencyCor.cpp
    ${MTDSRCDIR}/src/PolynomialCorrection.cpp
    ${MTDSRCDIR}/src/Power.cpp
    ${MTDSRCDIR}/src/PowerLawCorrection.cpp
    ${MTDSRCDIR}/src/Q1D2.cpp
    ${MTDSRCDIR}/src/Q1DWeighted.cpp
    ${MTDSRCDIR}/src/Qhelper.cpp
    ${MTDSRCDIR}/src/Qxy.cpp
    ${MTDSRCDIR}/src/RadiusSum.cpp
    ${MTDSRCDIR}/src/RayTracerTester.cpp
    ${MTDSRCDIR}/src/ReadGroupsFromFile.cpp
    ${MTDSRCDIR}/src/RealFFT.cpp
    ${MTDSRCDIR}/src/Rebin.cpp
    ${MTDSRCDIR}/src/Rebin2D.cpp
    ${MTDSRCDIR}/src/RebinByPulseTimes.cpp
    ${MTDSRCDIR}/src/RebinByTimeAtSample.cpp
    ${MTDSRCDIR}/src/RebinByTimeBase.cpp
    ${MTDSRCDIR}/src/RebinRagged2.cpp
    ${MTDSRCDIR}/src/RebinToWorkspace.cpp
    ${MTDSRCDIR}/src/Rebunch.cpp
    ${MTDSRCDIR}/src/Regroup.cpp
    ${MTDSRCDIR}/src/RemoveBackground.cpp
    ${MTDSRCDIR}/src/RemoveBins.cpp
    ${MTDSRCDIR}/src/RemoveInstrumentGeometry.cpp
    ${MTDSRCDIR}/src/RemoveLowResTOF.cpp
    ${MTDSRCDIR}/src/RemoveMaskedSpectra.cpp
    ${MTDSRCDIR}/src/RemovePromptPulse.cpp
    ${MTDSRCDIR}/src/RemoveSpectra.cpp
    ${MTDSRCDIR}/src/RemoveWorkspaceHistory.cpp
    ${MTDSRCDIR}/src/RenameWorkspace.cpp
    ${MTDSRCDIR}/src/RenameWorkspaces.cpp
    ${MTDSRCDIR}/src/ReplaceSpecialValues.cpp
    ${MTDSRCDIR}/src/ResampleX.cpp
    ${MTDSRCDIR}/src/ResetNegatives.cpp
    ${MTDSRCDIR}/src/ResizeRectangularDetector.cpp
    ${MTDSRCDIR}/src/RingProfile.cpp
    ${MTDSRCDIR}/src/RunCombinationHelpers/RunCombinationHelper.cpp
    ${MTDSRCDIR}/src/RunCombinationHelpers/SampleLogsBehaviour.cpp
    ${MTDSRCDIR}/src/SANSCollimationLengthEstimator.cpp
    ${MTDSRCDIR}/src/SampleCorrections/CircularBeamProfile.cpp
    ${MTDSRCDIR}/src/SampleCorrections/DetectorGridDefinition.cpp
    ${MTDSRCDIR}/src/SampleCorrections/MCAbsorptionStrategy.cpp
    ${MTDSRCDIR}/src/SampleCorrections/MCInteractionStatistics.cpp
    ${MTDSRCDIR}/src/SampleCorrections/MCInteractionVolume.cpp
    ${MTDSRCDIR}/src/SampleCorrections/MayersSampleCorrection.cpp
    ${MTDSRCDIR}/src/SampleCorrections/MayersSampleCorrectionStrategy.cpp
    ${MTDSRCDIR}/src/SampleCorrections/RectangularBeamProfile.cpp
    ${MTDSRCDIR}/src/SampleCorrections/SparseWorkspace.cpp
    ${MTDSRCDIR}/src/SassenaFFT.cpp
    ${MTDSRCDIR}/src/Scale.cpp
    ${MTDSRCDIR}/src/ScaleX.cpp
    ${MTDSRCDIR}/src/Segfault.cpp
    ${MTDSRCDIR}/src/SetInstrumentParameter.cpp
    ${MTDSRCDIR}/src/SetUncertainties.cpp
    ${MTDSRCDIR}/src/ShiftLogTime.cpp
    ${MTDSRCDIR}/src/SignalOverError.cpp
    ${MTDSRCDIR}/src/SmoothData.cpp
    ${MTDSRCDIR}/src/SmoothNeighbours.cpp
    ${MTDSRCDIR}/src/SofQCommon.cpp
    ${MTDSRCDIR}/src/SofQW.cpp
    ${MTDSRCDIR}/src/SofQWCentre.cpp
    ${MTDSRCDIR}/src/SofQWNormalisedPolygon.cpp
    ${MTDSRCDIR}/src/SofQWPolygon.cpp
    ${MTDSRCDIR}/src/SolidAngle.cpp
    ${MTDSRCDIR}/src/SortEvents.cpp
    ${MTDSRCDIR}/src/SortXAxis.cpp
    ${MTDSRCDIR}/src/SpatialGrouping.cpp
    ${MTDSRCDIR}/src/SpectrumAlgorithm.cpp
    ${MTDSRCDIR}/src/SphericalAbsorption.cpp
    ${MTDSRCDIR}/src/Stitch.cpp
    ${MTDSRCDIR}/src/Stitch1D.cpp
    ${MTDSRCDIR}/src/Stitch1DMany.cpp
    ${MTDSRCDIR}/src/StripPeaks.cpp
    ${MTDSRCDIR}/src/StripVanadiumPeaks.cpp
    ${MTDSRCDIR}/src/StripVanadiumPeaks2.cpp
    ${MTDSRCDIR}/src/SumEventsByLogValue.cpp
    ${MTDSRCDIR}/src/SumNeighbours.cpp
    ${MTDSRCDIR}/src/SumOverlappingTubes.cpp
    ${MTDSRCDIR}/src/SumRowColumn.cpp
    ${MTDSRCDIR}/src/SumSpectra.cpp
    ${MTDSRCDIR}/src/TOFSANSResolution.cpp
    ${MTDSRCDIR}/src/TOFSANSResolutionByPixel.cpp
    ${MTDSRCDIR}/src/TOFSANSResolutionByPixelCalculator.cpp
    ${MTDSRCDIR}/src/TimeAtSampleStrategyDirect.cpp
    ${MTDSRCDIR}/src/TimeAtSampleStrategyElastic.cpp
    ${MTDSRCDIR}/src/TimeAtSampleStrategyIndirect.cpp
    ${MTDSRCDIR}/src/Transpose.cpp
    ${MTDSRCDIR}/src/UnGroupWorkspace.cpp
    ${MTDSRCDIR}/src/UnaryOperation.cpp
    ${MTDSRCDIR}/src/UnwrapMonitor.cpp
    ${MTDSRCDIR}/src/UnwrapMonitorsInTOF.cpp
    ${MTDSRCDIR}/src/UnwrapSNS.cpp
#   ${MTDSRCDIR}/src/UpdateScriptRepository.cpp
    ${MTDSRCDIR}/src/VesuvioL1ThetaResolution.cpp
    ${MTDSRCDIR}/src/WeightedMean.cpp
    ${MTDSRCDIR}/src/WeightedMeanOfWorkspace.cpp
    ${MTDSRCDIR}/src/WeightingStrategy.cpp
    ${MTDSRCDIR}/src/WienerSmooth.cpp
    ${MTDSRCDIR}/src/WorkflowAlgorithmRunner.cpp
    ${MTDSRCDIR}/src/WorkspaceBoundingBox.cpp
    ${MTDSRCDIR}/src/WorkspaceJoiners.cpp
    ${MTDSRCDIR}/src/XDataConverter.cpp
    ${MTDSRCDIR}/src/XrayAbsorptionCorrection.cpp
)

# Add the target for this directory
add_library(Algorithms OBJECT ${SRC_FILES})
target_include_directories(Algorithms PRIVATE
    ../inc
    ${MTDSRCDIR}/inc
    ../mantid/Framework/API/inc
    ../mantid/Framework/Beamline/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    ../mantid/Framework/Indexing/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/NexusCpp/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)
set_property(TARGET Algorithms PROPERTY POSITION_INDEPENDENT_CODE ON)
