set(MTDSRCDIR ../mantid/Framework/Crystal)
set(CRYSTAL_SRC_FILES
    #${MTDSRCDIR}/src/AddPeakHKL.cpp
    #${MTDSRCDIR}/src/AnvredCorrection.cpp
    #${MTDSRCDIR}/src/CalculatePeaksHKL.cpp
    #${MTDSRCDIR}/src/CalculateUMatrix.cpp
    #${MTDSRCDIR}/src/CalibrationHelpers.cpp
    #${MTDSRCDIR}/src/CentroidPeaks.cpp
    #${MTDSRCDIR}/src/ClearUB.cpp
    #${MTDSRCDIR}/src/Cluster.cpp
    #${MTDSRCDIR}/src/ClusterRegister.cpp
    #${MTDSRCDIR}/src/CombinePeaksWorkspaces.cpp
    #${MTDSRCDIR}/src/CompositeCluster.cpp
    #${MTDSRCDIR}/src/ConnectedComponentLabeling.cpp
    #${MTDSRCDIR}/src/ConvertPeaksWorkspace.cpp
    #${MTDSRCDIR}/src/CountReflections.cpp
    #${MTDSRCDIR}/src/DiffPeaksWorkspaces.cpp
    #${MTDSRCDIR}/src/DisjointElement.cpp
    #${MTDSRCDIR}/src/FilterPeaks.cpp
    #${MTDSRCDIR}/src/FindClusterFaces.cpp
    #${MTDSRCDIR}/src/FindGoniometerAngles.cpp
    #${MTDSRCDIR}/src/FindSXPeaks.cpp
    #${MTDSRCDIR}/src/FindSXPeaksHelper.cpp
    #${MTDSRCDIR}/src/FindUBUsingFFT.cpp
    #${MTDSRCDIR}/src/FindUBUsingIndexedPeaks.cpp
    #${MTDSRCDIR}/src/FindUBUsingLatticeParameters.cpp
    #${MTDSRCDIR}/src/GoniometerAnglesFromPhiRotation.cpp
    #${MTDSRCDIR}/src/HardThresholdBackground.cpp
    #${MTDSRCDIR}/src/HasUB.cpp
    #${MTDSRCDIR}/src/IndexPeaks.cpp
    #${MTDSRCDIR}/src/IndexSXPeaks.cpp
    #${MTDSRCDIR}/src/IntegratePeakTimeSlices.cpp
    #${MTDSRCDIR}/src/IntegratePeaksHybrid.cpp
    #${MTDSRCDIR}/src/IntegratePeaksUsingClusters.cpp
    #${MTDSRCDIR}/src/LoadHKL.cpp
    #${MTDSRCDIR}/src/LoadIsawPeaks.cpp
    #${MTDSRCDIR}/src/LoadIsawSpectrum.cpp
    ${MTDSRCDIR}/src/LoadIsawUB.cpp
    #${MTDSRCDIR}/src/MaskPeaksWorkspace.cpp
    #${MTDSRCDIR}/src/NormaliseVanadium.cpp
    #${MTDSRCDIR}/src/OptimizeCrystalPlacement.cpp
    #${MTDSRCDIR}/src/OptimizeLatticeForCellType.cpp
    #${MTDSRCDIR}/src/PeakAlgorithmHelpers.cpp
    #${MTDSRCDIR}/src/PeakBackground.cpp
    #${MTDSRCDIR}/src/PeakClusterProjection.cpp
    #${MTDSRCDIR}/src/PeakHKLErrors.cpp
    #${MTDSRCDIR}/src/PeakIntegration.cpp
    #${MTDSRCDIR}/src/PeakIntensityVsRadius.cpp
    #${MTDSRCDIR}/src/PeakStatisticsTools.cpp
    #${MTDSRCDIR}/src/PeaksInRegion.cpp
    #${MTDSRCDIR}/src/PeaksIntersection.cpp
    #${MTDSRCDIR}/src/PeaksOnSurface.cpp
    #${MTDSRCDIR}/src/PredictFractionalPeaks.cpp
    #${MTDSRCDIR}/src/PredictPeaks.cpp
    #${MTDSRCDIR}/src/PredictSatellitePeaks.cpp
    #${MTDSRCDIR}/src/SCDCalibratePanels.cpp
    #${MTDSRCDIR}/src/SCDCalibratePanels2.cpp
    #${MTDSRCDIR}/src/SCDCalibratePanels2ObjFunc.cpp
    #${MTDSRCDIR}/src/SCDPanelErrors.cpp
    #${MTDSRCDIR}/src/SaveHKL.cpp
    #${MTDSRCDIR}/src/SaveIsawPeaks.cpp
    #${MTDSRCDIR}/src/SaveIsawUB.cpp
    #${MTDSRCDIR}/src/SaveLauenorm.cpp
    #${MTDSRCDIR}/src/SelectCellOfType.cpp
    #${MTDSRCDIR}/src/SelectCellWithForm.cpp
    #${MTDSRCDIR}/src/SetCrystalLocation.cpp
    ${MTDSRCDIR}/src/SetGoniometer.cpp
    #${MTDSRCDIR}/src/SetSpecialCoordinates.cpp
    ${MTDSRCDIR}/src/SetUB.cpp
    #${MTDSRCDIR}/src/ShowPeakHKLOffsets.cpp
    #${MTDSRCDIR}/src/ShowPossibleCells.cpp
    #${MTDSRCDIR}/src/SortHKL.cpp
    #${MTDSRCDIR}/src/SortPeaksWorkspace.cpp
    #${MTDSRCDIR}/src/StatisticsOfPeaksWorkspace.cpp
    #${MTDSRCDIR}/src/TransformHKL.cpp
)

add_library(Crystal OBJECT ${CRYSTAL_SRC_FILES})
target_include_directories(Crystal PRIVATE
    ${MTDSRCDIR}/inc
    ../inc
    ../mantid/Framework/API/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    ../mantid/Framework/Indexing/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/Types/inc
    ../mantid/Framework/NexusCpp/inc
    ${Boost_INCLUDE_DIRS}
)
set_property(TARGET Crystal PROPERTY POSITION_INDEPENDENT_CODE ON)
