set(MTDSRCDIR ../mantid/Framework/CurveFitting)

set(CURVEFIT_SRC_FILES
   ${MTDSRCDIR}/src/Algorithms/CalculateChiSquared.cpp
   ${MTDSRCDIR}/src/Algorithms/CalculateCostFunction.cpp
   ${MTDSRCDIR}/src/Algorithms/ConvertToYSpace.cpp
   #${MTDSRCDIR}/src/Algorithms/ConvolutionFit.cpp
   #${MTDSRCDIR}/src/Algorithms/ConvolveWorkspaces.cpp
   #${MTDSRCDIR}/src/Algorithms/CrystalFieldEnergies.cpp
   ${MTDSRCDIR}/src/Algorithms/DoublePulseFit.cpp
   ${MTDSRCDIR}/src/Algorithms/EstimateFitParameters.cpp
   ${MTDSRCDIR}/src/Algorithms/EstimatePeakErrors.cpp
   ${MTDSRCDIR}/src/Algorithms/EvaluateFunction.cpp
   ${MTDSRCDIR}/src/Algorithms/Fit.cpp
   ${MTDSRCDIR}/src/Algorithms/Fit1D.cpp
   #${MTDSRCDIR}/src/Algorithms/FitPowderDiffPeaks.cpp
   #${MTDSRCDIR}/src/Algorithms/IqtFit.cpp
   #${MTDSRCDIR}/src/Algorithms/LeBailFit.cpp
   #${MTDSRCDIR}/src/Algorithms/LeBailFunction.cpp
   ${MTDSRCDIR}/src/Algorithms/NormaliseByPeakArea.cpp
   ${MTDSRCDIR}/src/Algorithms/PawleyFit.cpp
   #${MTDSRCDIR}/src/Algorithms/PlotPeakByLogValue.cpp
   #${MTDSRCDIR}/src/Algorithms/PlotPeakByLogValueHelper.cpp
   #${MTDSRCDIR}/src/Algorithms/ProfileChiSquared1D.cpp
   #${MTDSRCDIR}/src/Algorithms/QENSFitSequential.cpp
   #${MTDSRCDIR}/src/Algorithms/QENSFitSimultaneous.cpp
   #${MTDSRCDIR}/src/Algorithms/QENSFitUtilities.cpp
   #${MTDSRCDIR}/src/Algorithms/RefinePowderInstrumentParameters.cpp
   #${MTDSRCDIR}/src/Algorithms/RefinePowderInstrumentParameters3.cpp
   ${MTDSRCDIR}/src/Algorithms/SplineBackground.cpp
   ${MTDSRCDIR}/src/Algorithms/SplineInterpolation.cpp
   ${MTDSRCDIR}/src/Algorithms/SplineSmoothing.cpp
   #${MTDSRCDIR}/src/Algorithms/VesuvioCalculateGammaBackground.cpp
   #${MTDSRCDIR}/src/Algorithms/VesuvioCalculateMS.cpp
   ${MTDSRCDIR}/src/AugmentedLagrangianOptimizer.cpp
   ${MTDSRCDIR}/src/Constraints/BoundaryConstraint.cpp
   ${MTDSRCDIR}/src/CostFunctions/CostFuncFitting.cpp
   ${MTDSRCDIR}/src/CostFunctions/CostFuncLeastSquares.cpp
   ${MTDSRCDIR}/src/CostFunctions/CostFuncRwp.cpp
   ${MTDSRCDIR}/src/CostFunctions/CostFuncUnweightedLeastSquares.cpp
   ${MTDSRCDIR}/src/CostFunctions/CostFuncPoisson.cpp
   ${MTDSRCDIR}/src/ExcludeRangeFinder.cpp
   ${MTDSRCDIR}/src/FitMW.cpp
   ${MTDSRCDIR}/src/EigenComplexMatrix.cpp
   ${MTDSRCDIR}/src/EigenComplexVector.cpp
   ${MTDSRCDIR}/src/EigenMatrix.cpp
   ${MTDSRCDIR}/src/EigenMatrixView.cpp
   ${MTDSRCDIR}/src/EigenVector.cpp
   ${MTDSRCDIR}/src/EigenVectorView.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/BFGS_Minimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/DampedGaussNewtonMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/DerivMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/FABADAMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/FRConjugateGradientMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/LevenbergMarquardtMDMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/LevenbergMarquardtMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/PRConjugateGradientMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/SimplexMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/SteepestDescentMinimizer.cpp
   ${MTDSRCDIR}/src/FuncMinimizers/TrustRegionMinimizer.cpp
   ${MTDSRCDIR}/src/FunctionDomain1DSpectrumCreator.cpp
   #${MTDSRCDIR}/src/Functions/Abragam.cpp
   #${MTDSRCDIR}/src/Functions/ActivationK.cpp
   #${MTDSRCDIR}/src/Functions/ActivationmeV.cpp
   #${MTDSRCDIR}/src/Functions/AsymmetricPearsonVII.cpp
   ${MTDSRCDIR}/src/Functions/BSpline.cpp
   ${MTDSRCDIR}/src/Functions/BackToBackExponential.cpp
   ${MTDSRCDIR}/src/Functions/BackgroundFunction.cpp
   ${MTDSRCDIR}/src/Functions/BivariateNormal.cpp
   #${MTDSRCDIR}/src/Functions/Bk2BkExpConvPV.cpp
   ${MTDSRCDIR}/src/Functions/ChebfunBase.cpp
   #${MTDSRCDIR}/src/Functions/Chebyshev.cpp
   #${MTDSRCDIR}/src/Functions/ChudleyElliotSQE.cpp
   #${MTDSRCDIR}/src/Functions/ComptonPeakProfile.cpp
   #${MTDSRCDIR}/src/Functions/ComptonProfile.cpp
   #${MTDSRCDIR}/src/Functions/ComptonScatteringCountRate.cpp
   ${MTDSRCDIR}/src/Functions/Convolution.cpp
   #${MTDSRCDIR}/src/Functions/CriticalPeakRelaxationRate.cpp
   #${MTDSRCDIR}/src/Functions/CrystalElectricField.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldControl.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldFunction.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeaks.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeaksBase.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldMultiSpectrum.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeakUtils.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldSpectrum.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldHeatCapacity.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldMagnetisation.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldMoment.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldMultiSpectrum.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeakUtils.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeaks.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldPeaksBase.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldSpectrum.cpp
   #${MTDSRCDIR}/src/Functions/CrystalFieldSusceptibility.cpp
   ${MTDSRCDIR}/src/Functions/CubicSpline.cpp
   #${MTDSRCDIR}/src/Functions/DecoupAsymPowderMagLong.cpp
   #${MTDSRCDIR}/src/Functions/DecoupAsymPowderMagRot.cpp
   ${MTDSRCDIR}/src/Functions/DeltaFunction.cpp
   #${MTDSRCDIR}/src/Functions/DiffRotDiscreteCircle.cpp
   #${MTDSRCDIR}/src/Functions/DiffSphere.cpp
   #${MTDSRCDIR}/src/Functions/DynamicKuboToyabe.cpp
   #${MTDSRCDIR}/src/Functions/ElasticDiffRotDiscreteCircle.cpp
   #${MTDSRCDIR}/src/Functions/ElasticDiffSphere.cpp
   #${MTDSRCDIR}/src/Functions/ElasticIsoRotDiff.cpp
   #${MTDSRCDIR}/src/Functions/EndErfc.cpp
   #${MTDSRCDIR}/src/Functions/ExpDecay.cpp
   #${MTDSRCDIR}/src/Functions/ExpDecayMuon.cpp
   #${MTDSRCDIR}/src/Functions/ExpDecayOsc.cpp
   #${MTDSRCDIR}/src/Functions/FickDiffusionSQE.cpp
   ${MTDSRCDIR}/src/Functions/FlatBackground.cpp
   #${MTDSRCDIR}/src/Functions/FullprofPolynomial.cpp
   #${MTDSRCDIR}/src/Functions/FunctionQDepends.cpp
   #${MTDSRCDIR}/src/Functions/GausDecay.cpp
   #${MTDSRCDIR}/src/Functions/GausOsc.cpp
   ${MTDSRCDIR}/src/Functions/Gaussian.cpp
   #${MTDSRCDIR}/src/Functions/GaussianComptonProfile.cpp
   #${MTDSRCDIR}/src/Functions/GramCharlier.cpp
   #${MTDSRCDIR}/src/Functions/GramCharlierComptonProfile.cpp
   #${MTDSRCDIR}/src/Functions/HallRossSQE.cpp
   ${MTDSRCDIR}/src/Functions/IkedaCarpenterPV.cpp
   #${MTDSRCDIR}/src/Functions/InelasticDiffRotDiscreteCircle.cpp
   #${MTDSRCDIR}/src/Functions/InelasticDiffSphere.cpp
   #${MTDSRCDIR}/src/Functions/InelasticIsoRotDiff.cpp
   #${MTDSRCDIR}/src/Functions/IsoRotDiff.cpp
   #${MTDSRCDIR}/src/Functions/Keren.cpp
   ${MTDSRCDIR}/src/Functions/LinearBackground.cpp
   ${MTDSRCDIR}/src/Functions/LogNormal.cpp
   ${MTDSRCDIR}/src/Functions/Lorentzian.cpp
   #${MTDSRCDIR}/src/Functions/MagneticOrderParameter.cpp
   #${MTDSRCDIR}/src/Functions/Meier.cpp
   #${MTDSRCDIR}/src/Functions/MultivariateGaussianComptonProfile.cpp
   #${MTDSRCDIR}/src/Functions/MuonFInteraction.cpp
   #${MTDSRCDIR}/src/Functions/MuoniumDecouplingCurve.cpp
   #${MTDSRCDIR}/src/Functions/NeutronBk2BkExpConvPVoigt.cpp
   ${MTDSRCDIR}/src/Functions/PawleyFunction.cpp
   ${MTDSRCDIR}/src/Functions/PeakParameterFunction.cpp
   ${MTDSRCDIR}/src/Functions/Polynomial.cpp
   ${MTDSRCDIR}/src/Functions/PowerLaw.cpp
   #${MTDSRCDIR}/src/Functions/ProcessBackground.cpp
   ${MTDSRCDIR}/src/Functions/ProductFunction.cpp
   #${MTDSRCDIR}/src/Functions/ProductLinearExp.cpp
   #${MTDSRCDIR}/src/Functions/ProductQuadraticExp.cpp
   ${MTDSRCDIR}/src/Functions/PseudoVoigt.cpp
   ${MTDSRCDIR}/src/Functions/Quadratic.cpp
   #${MTDSRCDIR}/src/Functions/ReflectivityMulf.cpp
   #${MTDSRCDIR}/src/Functions/Resolution.cpp
   ${MTDSRCDIR}/src/Functions/SimpleChebfun.cpp
   #${MTDSRCDIR}/src/Functions/SmoothTransition.cpp
   #${MTDSRCDIR}/src/Functions/StaticKuboToyabe.cpp
   #${MTDSRCDIR}/src/Functions/StaticKuboToyabeTimesExpDecay.cpp
   #${MTDSRCDIR}/src/Functions/StaticKuboToyabeTimesGausDecay.cpp
   #${MTDSRCDIR}/src/Functions/StaticKuboToyabeTimesStretchExp.cpp
   #${MTDSRCDIR}/src/Functions/StretchExp.cpp
   #${MTDSRCDIR}/src/Functions/StretchExpMuon.cpp
   ${MTDSRCDIR}/src/Functions/TabulatedFunction.cpp
   #${MTDSRCDIR}/src/Functions/TeixeiraWaterSQE.cpp
   #${MTDSRCDIR}/src/Functions/ThermalNeutronBk2BkExpAlpha.cpp
   #${MTDSRCDIR}/src/Functions/ThermalNeutronBk2BkExpBeta.cpp
   #${MTDSRCDIR}/src/Functions/ThermalNeutronBk2BkExpConvPVoigt.cpp
   #${MTDSRCDIR}/src/Functions/ThermalNeutronBk2BkExpSigma.cpp
   #${MTDSRCDIR}/src/Functions/ThermalNeutronDtoTOFFunction.cpp
   ${MTDSRCDIR}/src/Functions/UserFunction.cpp
   ${MTDSRCDIR}/src/Functions/UserFunction1D.cpp
   #${MTDSRCDIR}/src/Functions/VesuvioResolution.cpp
   ${MTDSRCDIR}/src/Functions/Voigt.cpp
   #${MTDSRCDIR}/src/Functions/ConvTempCorrection.cpp
   ${MTDSRCDIR}/src/GSLFunctions.cpp
   ${MTDSRCDIR}/src/GeneralDomainCreator.cpp
   ${MTDSRCDIR}/src/HistogramDomainCreator.cpp
   ${MTDSRCDIR}/src/IFittingAlgorithm.cpp
   ${MTDSRCDIR}/src/IMWDomainCreator.cpp
   ${MTDSRCDIR}/src/LatticeDomainCreator.cpp
   ${MTDSRCDIR}/src/LatticeFunction.cpp
   ${MTDSRCDIR}/src/MSVesuvioHelpers.cpp
   ${MTDSRCDIR}/src/MultiDomainCreator.cpp
   ${MTDSRCDIR}/src/MuonHelpers.cpp
   ${MTDSRCDIR}/src/ParDomain.cpp
   ${MTDSRCDIR}/src/ParameterEstimator.cpp
   ${MTDSRCDIR}/src/RalNlls/TrustRegion.cpp
   ${MTDSRCDIR}/src/RalNlls/Workspaces.cpp
   ${MTDSRCDIR}/src/SeqDomain.cpp
   ${MTDSRCDIR}/src/SeqDomainSpectrumCreator.cpp
   ${MTDSRCDIR}/src/SpecialFunctionHelper.cpp
   ${MTDSRCDIR}/src/TableWorkspaceDomainCreator.cpp
)

# Add the target for this directory
add_library(CurveFitting OBJECT ${CURVEFIT_SRC_FILES})

target_include_directories(CurveFitting PRIVATE
    ../inc
    ../mantid/Framework/API/inc
    ../mantid/Framework/CurveFitting/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/Nexus/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)
set_property(TARGET CurveFitting PROPERTY POSITION_INDEPENDENT_CODE ON)
