set(MTDSRCDIR ../mantid/Framework/DataHandling)

set(DATAHANDLING_SRC_FILES
    ${MTDSRCDIR}/src/ApplyDiffCal.cpp
    ${MTDSRCDIR}/src/BankPulseTimes.cpp
    ${MTDSRCDIR}/src/CheckMantidVersion.cpp
    ${MTDSRCDIR}/src/CompressEventAccumulator.cpp
    ${MTDSRCDIR}/src/CompressEvents.cpp
    ${MTDSRCDIR}/src/CreateChunkingFromInstrument.cpp
    ${MTDSRCDIR}/src/CreatePolarizationEfficiencies.cpp
    ${MTDSRCDIR}/src/CreatePolarizationEfficienciesBase.cpp
    ${MTDSRCDIR}/src/CreateSampleShape.cpp
    ${MTDSRCDIR}/src/CreateSimulationWorkspace.cpp
    ${MTDSRCDIR}/src/DataBlock.cpp
    ${MTDSRCDIR}/src/DataBlockComposite.cpp
    ${MTDSRCDIR}/src/DataBlockGenerator.cpp
    ${MTDSRCDIR}/src/DefaultEventLoader.cpp
    ${MTDSRCDIR}/src/DefineGaugeVolume.cpp
    ${MTDSRCDIR}/src/DeleteTableRows.cpp
    ${MTDSRCDIR}/src/DetermineChunking.cpp
    #${MTDSRCDIR}/src/DownloadFile.cpp
    ##${MTDSRCDIR}/src/DownloadInstrument.cpp
    ${MTDSRCDIR}/src/EventWorkspaceCollection.cpp
    ${MTDSRCDIR}/src/ExtractMonitorWorkspace.cpp
    ${MTDSRCDIR}/src/ExtractPolarizationEfficiencies.cpp
    ${MTDSRCDIR}/src/FindDetectorsInShape.cpp
    ${MTDSRCDIR}/src/FindDetectorsPar.cpp
    ${MTDSRCDIR}/src/GenerateGroupingPowder.cpp
    ${MTDSRCDIR}/src/GenerateGroupingPowder2.cpp
    ${MTDSRCDIR}/src/GroupDetectors.cpp
    ${MTDSRCDIR}/src/GroupDetectors2.cpp
    #${MTDSRCDIR}/src/ISISDataArchive.cpp
    #${MTDSRCDIR}/src/ISISJournal.cpp
    #${MTDSRCDIR}/src/ISISJournalGetExperimentRuns.cpp
    ${MTDSRCDIR}/src/JoinISISPolarizationEfficiencies.cpp
    ${MTDSRCDIR}/src/Load.cpp
    #${MTDSRCDIR}/src/LoadANSTOHelper.cpp
    ${MTDSRCDIR}/src/LoadAscii.cpp
    ${MTDSRCDIR}/src/LoadAscii2.cpp
    #${MTDSRCDIR}/src/LoadAsciiStl.cpp
    #${MTDSRCDIR}/src/LoadBBY.cpp
    ${MTDSRCDIR}/src/LoadBankFromDiskTask.cpp
    #${MTDSRCDIR}/src/LoadBinaryStl.cpp
    #${MTDSRCDIR}/src/LoadCSNSNexus.cpp
    ${MTDSRCDIR}/src/LoadCalFile.cpp
    #${MTDSRCDIR}/src/LoadCanSAS1D.cpp
    #${MTDSRCDIR}/src/LoadCanSAS1D2.cpp
    #${MTDSRCDIR}/src/LoadDNSEvent.cpp
    ${MTDSRCDIR}/src/LoadDaveGrp.cpp
    ${MTDSRCDIR}/src/LoadDetectorInfo.cpp
    ${MTDSRCDIR}/src/LoadDetectorsGroupingFile.cpp
    #${MTDSRCDIR}/src/LoadDiffCal.cpp
    #${MTDSRCDIR}/src/LoadDspacemap.cpp
    #${MTDSRCDIR}/src/LoadEMU.cpp
    ${MTDSRCDIR}/src/LoadEmptyInstrument.cpp
    ${MTDSRCDIR}/src/LoadErrorEventsNexus.cpp
    ${MTDSRCDIR}/src/LoadEventAsWorkspace2D.cpp
    ${MTDSRCDIR}/src/LoadEventNexus.cpp
    ${MTDSRCDIR}/src/LoadEventNexusIndexSetup.cpp
    ${MTDSRCDIR}/src/LoadEventPreNexus2.cpp
    #${MTDSRCDIR}/src/LoadFITS.cpp
    #${MTDSRCDIR}/src/LoadFullprofResolution.cpp
    #${MTDSRCDIR}/src/LoadGSASInstrumentFile.cpp
    #${MTDSRCDIR}/src/LoadGSS.cpp
    ${MTDSRCDIR}/src/LoadGeometry.cpp
    #${MTDSRCDIR}/src/LoadHFIRSANS.cpp
    ${MTDSRCDIR}/src/LoadHelper.cpp
    ${MTDSRCDIR}/src/LoadIDFFromNexus.cpp
    #${MTDSRCDIR}/src/LoadILLDiffraction.cpp
    #${MTDSRCDIR}/src/LoadILLIndirect2.cpp
    #${MTDSRCDIR}/src/LoadILLLagrange.cpp
    #${MTDSRCDIR}/src/LoadILLPolarizationFactors.cpp
    #${MTDSRCDIR}/src/LoadILLPolarizedDiffraction.cpp
    #${MTDSRCDIR}/src/LoadILLReflectometry.cpp
    #${MTDSRCDIR}/src/LoadILLSALSA.cpp
    #${MTDSRCDIR}/src/LoadILLSANS.cpp
    #${MTDSRCDIR}/src/LoadILLTOF2.cpp
    ${MTDSRCDIR}/src/LoadISISNexus2.cpp
    ${MTDSRCDIR}/src/LoadISISNexusHelper.cpp
    ${MTDSRCDIR}/src/LoadISISPolarizationEfficiencies.cpp
    ${MTDSRCDIR}/src/LoadInstrument.cpp
    ${MTDSRCDIR}/src/LoadInstrumentFromNexus.cpp
    ${MTDSRCDIR}/src/LoadInstrumentFromRaw.cpp
    #${MTDSRCDIR}/src/LoadIsawDetCal.cpp
    #${MTDSRCDIR}/src/LoadLLB.cpp
    ${MTDSRCDIR}/src/LoadLog.cpp
    #${MTDSRCDIR}/src/LoadMLZ.cpp
    ${MTDSRCDIR}/src/LoadMappingTable.cpp
    ${MTDSRCDIR}/src/LoadMask.cpp
    ${MTDSRCDIR}/src/LoadMcStas.cpp
    ${MTDSRCDIR}/src/LoadMcStasNexus.cpp
    #${MTDSRCDIR}/src/LoadMuonLog.cpp
    #${MTDSRCDIR}/src/LoadMuonNexusV2.cpp
    #${MTDSRCDIR}/src/LoadMuonNexusV2NexusHelper.cpp
    #${MTDSRCDIR}/src/LoadMuonStrategy.cpp
    ${MTDSRCDIR}/src/LoadNGEM.cpp
    ${MTDSRCDIR}/src/LoadNXSPE.cpp
    #${MTDSRCDIR}/src/LoadNXcanSAS.cpp
    ${MTDSRCDIR}/src/LoadNexus.cpp
    ${MTDSRCDIR}/src/LoadNexusLogs.cpp
    ${MTDSRCDIR}/src/LoadNexusMonitors.cpp
    ${MTDSRCDIR}/src/LoadNexusMonitors2.cpp
    ${MTDSRCDIR}/src/LoadNexusProcessed.cpp
    ${MTDSRCDIR}/src/LoadNexusProcessed2.cpp
    #${MTDSRCDIR}/src/LoadOff.cpp
    #${MTDSRCDIR}/src/LoadPDFgetNFile.cpp
    #${MTDSRCDIR}/src/LoadPLN.cpp
    #${MTDSRCDIR}/src/LoadPSIMuonBin.cpp
    ${MTDSRCDIR}/src/LoadParameterFile.cpp
    ${MTDSRCDIR}/src/LoadPreNexus.cpp
    ${MTDSRCDIR}/src/LoadPreNexusMonitors.cpp
    #${MTDSRCDIR}/src/LoadQKK.cpp
    #${MTDSRCDIR}/src/LoadRKH.cpp
    ${MTDSRCDIR}/src/LoadRaw/byte_rel_comp.cpp
    ${MTDSRCDIR}/src/LoadRaw/isisraw.cpp
    ${MTDSRCDIR}/src/LoadRaw/isisraw2.cpp
    ${MTDSRCDIR}/src/LoadRaw/item_struct.cpp
    ${MTDSRCDIR}/src/LoadRaw/vms_convert.cpp
    ${MTDSRCDIR}/src/LoadRaw3.cpp
    ${MTDSRCDIR}/src/LoadRawBin0.cpp
    ${MTDSRCDIR}/src/LoadRawHelper.cpp
    ${MTDSRCDIR}/src/LoadRawSpectrum0.cpp
    #${MTDSRCDIR}/src/LoadSESANS.cpp
    #${MTDSRCDIR}/src/LoadSINQFocus.cpp
    #${MTDSRCDIR}/src/LoadSNSspec.cpp
    ${MTDSRCDIR}/src/LoadSPE.cpp
    ${MTDSRCDIR}/src/LoadSampleDetailsFromRaw.cpp
    #${MTDSRCDIR}/src/LoadSampleEnvironment.cpp
    #${MTDSRCDIR}/src/LoadSampleShape.cpp
    #${MTDSRCDIR}/src/LoadSassena.cpp
    #${MTDSRCDIR}/src/LoadSingleMesh.cpp
    ${MTDSRCDIR}/src/LoadSpec.cpp
    #${MTDSRCDIR}/src/LoadSpice2D.cpp
    #${MTDSRCDIR}/src/LoadSpiceAscii.cpp
    #${MTDSRCDIR}/src/LoadSpiceXML2DDet.cpp
    #${MTDSRCDIR}/src/LoadStl.cpp
    #${MTDSRCDIR}/src/LoadSwans.cpp
    #${MTDSRCDIR}/src/LoadTBL.cpp
    ${MTDSRCDIR}/src/LoadTOFRawNexus.cpp
    ${MTDSRCDIR}/src/MaskDetectors.cpp
    ${MTDSRCDIR}/src/MaskDetectorsInShape.cpp
    ${MTDSRCDIR}/src/MaskSpectra.cpp
    #${MTDSRCDIR}/src/MeshFileIO.cpp
    ${MTDSRCDIR}/src/ModifyDetectorDotDatFile.cpp
    ${MTDSRCDIR}/src/MoveInstrumentComponent.cpp
    #${MTDSRCDIR}/src/MultiPeriodLoadMuonStrategy.cpp
    #${MTDSRCDIR}/src/NXcanSASHelper.cpp
    ${MTDSRCDIR}/src/NexusTester.cpp
    ##${MTDSRCDIR}/src/ORNLDataArchive.cpp
    #${MTDSRCDIR}/src/PDLoadCharacterizations.cpp
    ##${MTDSRCDIR}/src/ParallelEventLoader.cpp
    #${MTDSRCDIR}/src/PatchBBY.cpp
    ${MTDSRCDIR}/src/ProcessBankCompressed.cpp
    ${MTDSRCDIR}/src/ProcessBankData.cpp
    ${MTDSRCDIR}/src/PulseIndexer.cpp
    ${MTDSRCDIR}/src/RawFileInfo.cpp
    ${MTDSRCDIR}/src/ReadMaterial.cpp
    ${MTDSRCDIR}/src/RemoveLogs.cpp
    ${MTDSRCDIR}/src/RenameLog.cpp
    ${MTDSRCDIR}/src/RotateInstrumentComponent.cpp
    ${MTDSRCDIR}/src/RotateSource.cpp
    #${MTDSRCDIR}/src/SNSAppendGeometryToNexus.cpp
    #${MTDSRCDIR}/src/SampleEnvironmentFactory.cpp
    #${MTDSRCDIR}/src/SampleEnvironmentSpec.cpp
    #${MTDSRCDIR}/src/SampleEnvironmentSpecParser.cpp
    ${MTDSRCDIR}/src/SaveAscii.cpp
    ${MTDSRCDIR}/src/SaveAscii2.cpp
    #${MTDSRCDIR}/src/SaveBankScatteringAngles.cpp
    ${MTDSRCDIR}/src/SaveCSV.cpp
    ${MTDSRCDIR}/src/SaveCalFile.cpp
    #${MTDSRCDIR}/src/SaveCanSAS1D.cpp
    #${MTDSRCDIR}/src/SaveCanSAS1D2.cpp
    #${MTDSRCDIR}/src/SaveDaveGrp.cpp
    ${MTDSRCDIR}/src/SaveDetectorsGrouping.cpp
    #${MTDSRCDIR}/src/SaveDiffCal.cpp
    #${MTDSRCDIR}/src/SaveDspacemap.cpp
    #${MTDSRCDIR}/src/SaveFITS.cpp
    ${MTDSRCDIR}/src/SaveFocusedXYE.cpp
    #${MTDSRCDIR}/src/SaveFullprofResolution.cpp
    #${MTDSRCDIR}/src/SaveGDA.cpp
    #${MTDSRCDIR}/src/SaveGSASInstrumentFile.cpp
    #${MTDSRCDIR}/src/SaveGSS.cpp
    ${MTDSRCDIR}/src/SaveISISNexus.cpp
    #${MTDSRCDIR}/src/SaveIsawDetCal.cpp
    ${MTDSRCDIR}/src/SaveMask.cpp
    #${MTDSRCDIR}/src/SaveNISTDAT.cpp
    ${MTDSRCDIR}/src/SaveNXSPE.cpp
    #${MTDSRCDIR}/src/SaveNXTomo.cpp
    #${MTDSRCDIR}/src/SaveNXcanSAS.cpp
    #${MTDSRCDIR}/src/SaveNXcanSASBase.cpp
    ${MTDSRCDIR}/src/SaveNexus.cpp
    #${MTDSRCDIR}/src/SaveNexusESS.cpp
    #${MTDSRCDIR}/src/SaveNexusGeometry.cpp
    ${MTDSRCDIR}/src/SaveNexusProcessed.cpp
    #${MTDSRCDIR}/src/SaveOpenGenieAscii.cpp
    ${MTDSRCDIR}/src/SavePAR.cpp
    #${MTDSRCDIR}/src/SavePDFGui.cpp
    ${MTDSRCDIR}/src/SavePHX.cpp
    ${MTDSRCDIR}/src/SaveParameterFile.cpp
    #${MTDSRCDIR}/src/SaveRKH.cpp
    #${MTDSRCDIR}/src/SaveRMCProfile.cpp
    #${MTDSRCDIR}/src/SaveReflectometryAscii.cpp
    #${MTDSRCDIR}/src/SaveSESANS.cpp
    ${MTDSRCDIR}/src/SaveSPE.cpp
    #${MTDSRCDIR}/src/SaveSampleEnvironmentAndShape.cpp
    #${MTDSRCDIR}/src/SaveStl.cpp
    #${MTDSRCDIR}/src/SaveTBL.cpp
    #${MTDSRCDIR}/src/SaveToSNSHistogramNexus.cpp
    #${MTDSRCDIR}/src/SaveVTK.cpp
    ${MTDSRCDIR}/src/ScaleInstrumentComponent.cpp
    ${MTDSRCDIR}/src/SetBeam.cpp
    #${MTDSRCDIR}/src/SetSample.cpp
    ${MTDSRCDIR}/src/SetSampleMaterial.cpp
    #${MTDSRCDIR}/src/SetScalingPSD.cpp
    #${MTDSRCDIR}/src/SinglePeriodLoadMuonStrategy.cpp
    ${MTDSRCDIR}/src/SortTableWorkspace.cpp
    ${MTDSRCDIR}/src/StartAndEndTimeFromNexusFileExtractor.cpp
    ${MTDSRCDIR}/src/UpdateInstrumentFromFile.cpp
    ${MTDSRCDIR}/src/XmlHandler.cpp
    ${MTDSRCDIR}/src/RotateSampleShape.cpp
)

add_library(DataHandling OBJECT ${DATAHANDLING_SRC_FILES})
target_include_directories(DataHandling PUBLIC
    ../inc
    ${MTDSRCDIR}/inc
    ../mantid/Framework/API/inc
    ../mantid/Framework/Beamline/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    ../mantid/Framework/Indexing/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/Json/inc
    ../mantid/Framework/NexusCpp/inc
    ../mantid/Framework/Nexus/inc
    ../mantid/Framework/NexusGeometry/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)
set_property(TARGET DataHandling PROPERTY POSITION_INDEPENDENT_CODE ON)
