set(DATAOBJ_SRC_FILES
    #../mantid/Framework/DataObjects/src/AffineMatrixParameter.cpp
    #../mantid/Framework/DataObjects/src/AffineMatrixParameterParser.cpp
    #../mantid/Framework/DataObjects/src/BoxControllerNeXusIO.cpp
    #../mantid/Framework/DataObjects/src/CoordTransformAffine.cpp
    #../mantid/Framework/DataObjects/src/CoordTransformAffineParser.cpp
    #../mantid/Framework/DataObjects/src/CoordTransformAligned.cpp
    ../mantid/Framework/DataObjects/src/CoordTransformDistance.cpp
    #../mantid/Framework/DataObjects/src/CoordTransformDistanceParser.cpp
    ../mantid/Framework/DataObjects/src/EventList.cpp
    ../mantid/Framework/DataObjects/src/EventWorkspace.cpp
    #../mantid/Framework/DataObjects/src/EventWorkspaceHelpers.cpp
    ../mantid/Framework/DataObjects/src/EventWorkspaceMRU.cpp
    ../mantid/Framework/DataObjects/src/Events.cpp
    ../mantid/Framework/DataObjects/src/FakeMD.cpp
    ../mantid/Framework/DataObjects/src/FractionalRebinning.cpp
    ../mantid/Framework/DataObjects/src/GroupingWorkspace.cpp
    ../mantid/Framework/DataObjects/src/Histogram1D.cpp
    ../mantid/Framework/DataObjects/src/MDBoxFlatTree.cpp
    ../mantid/Framework/DataObjects/src/MDBoxSaveable.cpp
    ../mantid/Framework/DataObjects/src/MDEventFactory.cpp
    ../mantid/Framework/DataObjects/src/MDFramesToSpecialCoordinateSystem.cpp
    ../mantid/Framework/DataObjects/src/MDHistoWorkspace.cpp
    ../mantid/Framework/DataObjects/src/MDHistoWorkspaceIterator.cpp
    ../mantid/Framework/DataObjects/src/MDLeanEvent.cpp
    ../mantid/Framework/DataObjects/src/MaskWorkspace.cpp
    #../mantid/Framework/DataObjects/src/MementoTableWorkspace.cpp
    ../mantid/Framework/DataObjects/src/NoShape.cpp
    ../mantid/Framework/DataObjects/src/OffsetsWorkspace.cpp
    ../mantid/Framework/DataObjects/src/Peak.cpp
    ../mantid/Framework/DataObjects/src/LeanElasticPeak.cpp
    ../mantid/Framework/DataObjects/src/BasePeak.cpp
    ../mantid/Framework/DataObjects/src/PeakColumn.cpp
    ../mantid/Framework/DataObjects/src/PeakNoShapeFactory.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeBase.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeEllipsoid.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeEllipsoidFactory.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeSpherical.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeSphericalFactory.cpp
    ../mantid/Framework/DataObjects/src/PeaksWorkspace.cpp
    ../mantid/Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
    ../mantid/Framework/DataObjects/src/PropertyWithValue.cpp
    ../mantid/Framework/DataObjects/src/RebinnedOutput.cpp
    #../mantid/Framework/DataObjects/src/ReflectometryTransform.cpp
    ../mantid/Framework/DataObjects/src/ScanningWorkspaceBuilder.cpp
    ../mantid/Framework/DataObjects/src/SpecialWorkspace2D.cpp
    ../mantid/Framework/DataObjects/src/SplittersWorkspace.cpp
    #../mantid/Framework/DataObjects/src/TableColumn.cpp
    ../mantid/Framework/DataObjects/src/TableWorkspace.cpp
    ../mantid/Framework/DataObjects/src/TableWorkspaceNotEmptyValidator.cpp
    ../mantid/Framework/DataObjects/src/TimeSplitter.cpp
    #../mantid/Framework/DataObjects/src/VectorColumn.cpp
    ../mantid/Framework/DataObjects/src/Workspace2D.cpp
    ../mantid/Framework/DataObjects/src/WorkspaceCreation.cpp
    ../mantid/Framework/DataObjects/src/WorkspaceProperty.cpp
    ../mantid/Framework/DataObjects/src/WorkspaceSingleValue.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeDetectorBin.cpp
    ../mantid/Framework/DataObjects/src/PeakShapeDetectorBinFactory.cpp
)
add_library(DataObjects OBJECT ${DATAOBJ_SRC_FILES})
target_include_directories(DataObjects PUBLIC
    ../inc
    ../mantid/Framework/API/inc
    ../mantid/Framework/Beamline/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    ../mantid/Framework/Indexing/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/Json/inc
    ../mantid/Framework/NexusCpp/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)
set_property(TARGET DataObjects PROPERTY POSITION_INDEPENDENT_CODE ON)
