set(GEOMETRY_SRC_FILES
    ../mantid/Framework/Geometry/src/Crystal/BraggScatterer.cpp
    ../mantid/Framework/Geometry/src/Crystal/BraggScattererFactory.cpp
    ../mantid/Framework/Geometry/src/Crystal/BraggScattererInCrystalStructure.cpp
    ../mantid/Framework/Geometry/src/Crystal/CenteringGroup.cpp
    ../mantid/Framework/Geometry/src/Crystal/CompositeBraggScatterer.cpp
    ../mantid/Framework/Geometry/src/Crystal/CrystalStructure.cpp
    ../mantid/Framework/Geometry/src/Crystal/CyclicGroup.cpp
    ../mantid/Framework/Geometry/src/Crystal/Group.cpp
    ../mantid/Framework/Geometry/src/Crystal/GroupTransformation.cpp
    ../mantid/Framework/Geometry/src/Crystal/IsotropicAtomBraggScatterer.cpp
    ../mantid/Framework/Geometry/src/Crystal/OrientedLattice.cpp
    ../mantid/Framework/Geometry/src/Crystal/PointGroup.cpp
    ../mantid/Framework/Geometry/src/Crystal/PointGroupFactory.cpp
    ../mantid/Framework/Geometry/src/Crystal/ProductOfCyclicGroups.cpp
    ../mantid/Framework/Geometry/src/Crystal/ReflectionCondition.cpp
    ../mantid/Framework/Geometry/src/Crystal/SpaceGroup.cpp
    ../mantid/Framework/Geometry/src/Crystal/SpaceGroupFactory.cpp
    ../mantid/Framework/Geometry/src/Crystal/SymmetryElement.cpp
    ../mantid/Framework/Geometry/src/Crystal/SymmetryElementFactory.cpp
    ../mantid/Framework/Geometry/src/Crystal/SymmetryOperation.cpp
    ../mantid/Framework/Geometry/src/Crystal/SymmetryOperationFactory.cpp
    ../mantid/Framework/Geometry/src/Crystal/SymmetryOperationSymbolParser.cpp
    ../mantid/Framework/Geometry/src/Crystal/UnitCell.cpp
    ../mantid/Framework/Geometry/src/Crystal/V3R.cpp
    ../mantid/Framework/Geometry/src/IObjComponent.cpp
    ../mantid/Framework/Geometry/src/Instrument.cpp
    ../mantid/Framework/Geometry/src/Instrument/Component.cpp
    ../mantid/Framework/Geometry/src/Instrument/ComponentInfo.cpp
    ../mantid/Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp
    ../mantid/Framework/Geometry/src/Instrument/CompAssembly.cpp
    ../mantid/Framework/Geometry/src/Instrument/DetectorInfo.cpp
    ../mantid/Framework/Geometry/src/Instrument/DetectorGroup.cpp
    ../mantid/Framework/Geometry/src/Instrument/Detector.cpp
    ../mantid/Framework/Geometry/src/Instrument/FitParameter.cpp
    ../mantid/Framework/Geometry/src/Instrument/GridDetector.cpp
    ../mantid/Framework/Geometry/src/Instrument/GridDetectorPixel.cpp
    ../mantid/Framework/Geometry/src/Instrument/Goniometer.cpp
    ../mantid/Framework/Geometry/src/Instrument/IDFObject.cpp
    ../mantid/Framework/Geometry/src/Instrument/InstrumentDefinitionParser.cpp
    ../mantid/Framework/Geometry/src/Instrument/InstrumentVisitor.cpp
    ../mantid/Framework/Geometry/src/Instrument/ObjCompAssembly.cpp
    ../mantid/Framework/Geometry/src/Instrument/ObjComponent.cpp
    ../mantid/Framework/Geometry/src/Instrument/Parameter.cpp
    ../mantid/Framework/Geometry/src/Instrument/ParameterMap.cpp
    ../mantid/Framework/Geometry/src/Instrument/ParComponentFactory.cpp
    ../mantid/Framework/Geometry/src/Instrument/RectangularDetector.cpp
    ../mantid/Framework/Geometry/src/Instrument/ReferenceFrame.cpp
    ../mantid/Framework/Geometry/src/Instrument/StructuredDetector.cpp
    ../mantid/Framework/Geometry/src/Instrument/XMLInstrumentParameter.cpp
    ../mantid/Framework/Geometry/src/MDGeometry/GeneralFrame.cpp
    ../mantid/Framework/Geometry/src/MDGeometry/MDGeometryXMLBuilder.cpp
    ../mantid/Framework/Geometry/src/MDGeometry/MDHistoDimension.cpp
    ../mantid/Framework/Geometry/src/Math/PolyBase.cpp
    ../mantid/Framework/Geometry/src/Math/Triple.cpp
    ../mantid/Framework/Geometry/src/Math/mathSupport.cpp
    ../mantid/Framework/Geometry/src/Objects/BoundingBox.cpp
    ../mantid/Framework/Geometry/src/Objects/CSGObject.cpp
    ../mantid/Framework/Geometry/src/Objects/MeshObject.cpp
    ../mantid/Framework/Geometry/src/Objects/MeshObject2D.cpp
    ../mantid/Framework/Geometry/src/Objects/MeshObjectCommon.cpp
    ../mantid/Framework/Geometry/src/Objects/Rules.cpp
    ../mantid/Framework/Geometry/src/Objects/RuleItems.cpp
    ../mantid/Framework/Geometry/src/Objects/ShapeFactory.cpp
    ../mantid/Framework/Geometry/src/Objects/Track.cpp
    ../mantid/Framework/Geometry/src/RandomPoint.cpp
    ../mantid/Framework/Geometry/src/Rendering/GeometryHandler.cpp
    ../mantid/Framework/Geometry/src/Rendering/GeometryTriangulator.cpp
    ../mantid/Framework/Geometry/src/Rendering/vtkGeometryCacheReader.cpp
    ../mantid/Framework/Geometry/src/Rendering/vtkGeometryCacheWriter.cpp
    ../mantid/Framework/Geometry/src/Rendering/RenderingHelpersThrowing.cpp
    ../mantid/Framework/Geometry/src/Rendering/ShapeInfo.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Cone.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Cylinder.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Line.cpp
    ../mantid/Framework/Geometry/src/Surfaces/LineIntersectVisit.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Plane.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Quadratic.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Sphere.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Surface.cpp
    ../mantid/Framework/Geometry/src/Surfaces/Torus.cpp
)
add_library(Geometry OBJECT ${GEOMETRY_SRC_FILES})
target_include_directories(Geometry PRIVATE
    ../inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/Beamline/inc
    ../mantid/Framework/Json/inc
    ../mantid/Framework/Kernel/inc
    ../mantid/Framework/NexusCpp/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIRS}
)
set_property(TARGET Geometry PROPERTY POSITION_INDEPENDENT_CODE ON)
