set(MTDSRCDIR ../mantid/Framework/MDAlgorithms)

set(MDALGO_SRC_FILES
    ${MTDSRCDIR}/src/AccumulateMD.cpp
    ${MTDSRCDIR}/src/AndMD.cpp
    ${MTDSRCDIR}/src/ApplyDetailedBalanceMD.cpp
    ${MTDSRCDIR}/src/BaseConvertToDiffractionMDWorkspace.cpp
    ${MTDSRCDIR}/src/BinMD.cpp
    ${MTDSRCDIR}/src/BinaryOperationMD.cpp
    ${MTDSRCDIR}/src/BooleanBinaryOperationMD.cpp
    ${MTDSRCDIR}/src/CalculateCoverageDGS.cpp
    #${MTDSRCDIR}/src/CentroidPeaksMD.cpp
    #${MTDSRCDIR}/src/CentroidPeaksMD2.cpp
    ${MTDSRCDIR}/src/ChangeQConvention.cpp
    ${MTDSRCDIR}/src/CloneMDWorkspace.cpp
    ${MTDSRCDIR}/src/CompactMD.cpp
    ${MTDSRCDIR}/src/CompareMDWorkspaces.cpp
    ${MTDSRCDIR}/src/ConvToMDBase.cpp
    ${MTDSRCDIR}/src/ConvToMDEventsWS.cpp
    ${MTDSRCDIR}/src/ConvToMDEventsWSIndexing.cpp
    ${MTDSRCDIR}/src/ConvToMDHistoWS.cpp
    ${MTDSRCDIR}/src/ConvToMDSelector.cpp
    #${MTDSRCDIR}/src/ConvertCWPDMDToSpectra.cpp
    #${MTDSRCDIR}/src/ConvertCWSDExpToMomentum.cpp
    #${MTDSRCDIR}/src/ConvertCWSDMDtoHKL.cpp
    #${MTDSRCDIR}/src/ConvertHFIRSCDtoMDE.cpp
    ${MTDSRCDIR}/src/ConvertMDHistoToMatrixWorkspace.cpp
    #${MTDSRCDIR}/src/ConvertSpiceDataToRealSpace.cpp
    #${MTDSRCDIR}/src/ConvertToDetectorFaceMD.cpp
    #${MTDSRCDIR}/src/ConvertToDiffractionMDWorkspace.cpp
    #${MTDSRCDIR}/src/ConvertToDiffractionMDWorkspace2.cpp
    #${MTDSRCDIR}/src/ConvertToDiffractionMDWorkspace3.cpp
    ${MTDSRCDIR}/src/ConvertToMD.cpp
    ${MTDSRCDIR}/src/ConvertToMDMinMaxGlobal.cpp
    ${MTDSRCDIR}/src/ConvertToMDMinMaxLocal.cpp
    ${MTDSRCDIR}/src/ConvertToMDParent.cpp
    ${MTDSRCDIR}/src/CreateMD.cpp
    ${MTDSRCDIR}/src/CreateMDHistoWorkspace.cpp
    ${MTDSRCDIR}/src/CreateMDWorkspace.cpp
    ${MTDSRCDIR}/src/CutMD.cpp
    ${MTDSRCDIR}/src/DgsScatteredTransmissionCorrectionMD.cpp
    ${MTDSRCDIR}/src/DisplayNormalizationSetter.cpp
    ${MTDSRCDIR}/src/DivideMD.cpp
    ${MTDSRCDIR}/src/EqualToMD.cpp
    ${MTDSRCDIR}/src/EvaluateMDFunction.cpp
    ${MTDSRCDIR}/src/ExponentialMD.cpp
    ${MTDSRCDIR}/src/FakeMDEventData.cpp
    ${MTDSRCDIR}/src/FindPeaksMD.cpp
    ${MTDSRCDIR}/src/FitMD.cpp
    #${MTDSRCDIR}/src/FlippingRatioCorrectionMD.cpp
    #${MTDSRCDIR}/src/GetSpiceDataRawCountsFromMD.cpp
    ${MTDSRCDIR}/src/GreaterThanMD.cpp
    ${MTDSRCDIR}/src/IDynamicRebinning.cpp
    ${MTDSRCDIR}/src/ImportMDEventWorkspace.cpp
    ${MTDSRCDIR}/src/ImportMDHistoWorkspace.cpp
    ${MTDSRCDIR}/src/ImportMDHistoWorkspaceBase.cpp
    #${MTDSRCDIR}/src/Integrate3DEvents.cpp
    #${MTDSRCDIR}/src/IntegrateEllipsoids.cpp
    #${MTDSRCDIR}/src/IntegrateEllipsoidsTwoStep.cpp
    #${MTDSRCDIR}/src/IntegrateEllipsoidsV1.cpp
    #${MTDSRCDIR}/src/IntegrateEllipsoidsV2.cpp
    #${MTDSRCDIR}/src/IntegrateFlux.cpp
    #${MTDSRCDIR}/src/IntegrateMDHistoWorkspace.cpp
    #${MTDSRCDIR}/src/IntegratePeaksCWSD.cpp
    #${MTDSRCDIR}/src/IntegratePeaksMD.cpp
    #${MTDSRCDIR}/src/IntegratePeaksMD2.cpp
    #${MTDSRCDIR}/src/IntegratePeaksMDHKL.cpp
    #${MTDSRCDIR}/src/IntegrateQLabEvents.cpp
    ${MTDSRCDIR}/src/InvalidParameter.cpp
    ${MTDSRCDIR}/src/InvalidParameterParser.cpp
    ${MTDSRCDIR}/src/LessThanMD.cpp
    #${MTDSRCDIR}/src/LoadDNSSCD.cpp
    #${MTDSRCDIR}/src/LoadGaussCube.cpp
    ${MTDSRCDIR}/src/LoadMD.cpp
    ${MTDSRCDIR}/src/LoadSQW.cpp
    ${MTDSRCDIR}/src/LoadSQW2.cpp
    ${MTDSRCDIR}/src/LogarithmMD.cpp
    ${MTDSRCDIR}/src/MDEventWSWrapper.cpp
    ${MTDSRCDIR}/src/MDNorm.cpp
    ${MTDSRCDIR}/src/MDNormDirectSC.cpp
    ${MTDSRCDIR}/src/MDNormSCD.cpp
    ${MTDSRCDIR}/src/MDTransfAxisNames.cpp
    ${MTDSRCDIR}/src/MDTransfFactory.cpp
    ${MTDSRCDIR}/src/MDTransfModQ.cpp
    ${MTDSRCDIR}/src/MDTransfNoQ.cpp
    ${MTDSRCDIR}/src/MDTransfQ3D.cpp
    ${MTDSRCDIR}/src/MDWSDescription.cpp
    ${MTDSRCDIR}/src/MDWSTransform.cpp
    ${MTDSRCDIR}/src/MagneticFormFactorCorrectionMD.cpp
    ${MTDSRCDIR}/src/MaskMD.cpp
    ${MTDSRCDIR}/src/MergeMD.cpp
    ${MTDSRCDIR}/src/MergeMDFiles.cpp
    ${MTDSRCDIR}/src/MinusMD.cpp
    ${MTDSRCDIR}/src/MultiplyMD.cpp
    ${MTDSRCDIR}/src/NotMD.cpp
    ${MTDSRCDIR}/src/OrMD.cpp
    ${MTDSRCDIR}/src/PlusMD.cpp
    #${MTDSRCDIR}/src/PolarizationAngleCorrectionMD.cpp
    ${MTDSRCDIR}/src/PowerMD.cpp
    ${MTDSRCDIR}/src/PreprocessDetectorsToMD.cpp
    ${MTDSRCDIR}/src/QTransform.cpp
    ${MTDSRCDIR}/src/QueryMDWorkspace.cpp
    ${MTDSRCDIR}/src/RecalculateTrajectoriesExtents.cpp
    ${MTDSRCDIR}/src/ReplicateMD.cpp
    #${MTDSRCDIR}/src/SaveIsawQvector.cpp
    ${MTDSRCDIR}/src/SaveMD.cpp
    ${MTDSRCDIR}/src/SaveMD2.cpp
    #${MTDSRCDIR}/src/SaveZODS.cpp
    ${MTDSRCDIR}/src/SetMDFrame.cpp
    ${MTDSRCDIR}/src/SetMDUsingMask.cpp
    ${MTDSRCDIR}/src/SliceMD.cpp
    ${MTDSRCDIR}/src/SlicingAlgorithm.cpp
    ${MTDSRCDIR}/src/SmoothMD.cpp
    #${MTDSRCDIR}/src/ThresholdMD.cpp
    ${MTDSRCDIR}/src/TransformMD.cpp
    ${MTDSRCDIR}/src/TransposeMD.cpp
    ${MTDSRCDIR}/src/UnaryOperationMD.cpp
    ${MTDSRCDIR}/src/UnitsConversionHelper.cpp
    ${MTDSRCDIR}/src/UserFunctionMD.cpp
    ${MTDSRCDIR}/src/WeightedMeanMD.cpp
    ${MTDSRCDIR}/src/XorMD.cpp
)

add_library(MDAlgorithms OBJECT ${MDALGO_SRC_FILES})
target_include_directories(MDAlgorithms PUBLIC
    ../inc
    ${MTDSRCDIR}/inc
    ../mantid/Framework/API/inc
    #../mantid/Framework/Beamline/inc
    ../mantid/Framework/DataObjects/inc
    ../mantid/Framework/Geometry/inc
    ../mantid/Framework/HistogramData/inc
    #../mantid/Framework/Indexing/inc
    ../mantid/Framework/Kernel/inc
    #../mantid/Framework/Json/inc
    ../mantid/Framework/NexusCpp/inc
    #../mantid/Framework/Nexus/inc
    #../mantid/Framework/NexusGeometry/inc
    ../mantid/Framework/Types/inc
    ${Boost_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)
set_property(TARGET MDAlgorithms PROPERTY POSITION_INDEPENDENT_CODE ON)
