#ifndef MANTID_DATAOBJECTS_DLL_H
#define MANTID_DATAOBJECTS_DLL_H

#define MANTID_DATAOBJECTS_DLL
#define MANTID_DATAOBJECTS_NO_EXPORT

#ifndef MANTID_DATAOBJECTS_DEPRECATED
#  define MANTID_DATAOBJECTS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MANTID_DATAOBJECTS_DEPRECATED_EXPORT
#  define MANTID_DATAOBJECTS_DEPRECATED_EXPORT MANTID_DATAOBJECTS_DLL MANTID_DATAOBJECTS_DEPRECATED
#endif

#ifndef MANTID_DATAOBJECTS_DEPRECATED_NO_EXPORT
#  define MANTID_DATAOBJECTS_DEPRECATED_NO_EXPORT MANTID_DATAOBJECTS_NO_EXPORT MANTID_DATAOBJECTS_DEPRECATED
#endif

#ifndef DATAOBJECTS_DEPRECATED
    #define DATAOBJECTS_DEPRECATED(func) MANTID_DATAOBJECTS_DEPRECATED func
#endif

#ifndef UNUSED_ARG
    #define UNUSED_ARG(x) (void) x;
#endif

#include <cstdint>

#endif /* MANTID_DATAOBJECTS_DLL_H */
